import 'package:flutter/material.dart';
import 'package:flutter_web/pages/home/home_controller.dart';
import 'package:flutter_web/routes/app_pages.dart';
import 'package:get/get.dart';
import 'package:flutter/material.dart';

class HomePage extends StatelessWidget{
  final HomeController homeController = Get.find<HomeController>();
  
  @override
  Widget build(BuildContext context){
    MediaQueryData media = MediaQuery.of(context);
    double page_padding = 200;
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        actions: [
          TextButton(onPressed: ()=>{}, child: Text('Home',style: TextStyle(color: Colors.black),)),
          TextButton(onPressed: ()=>{}, child: Text('Pricing',style: TextStyle(color: Colors.black),)),
          TextButton(onPressed: ()=>{}, child: Text('Help',style: TextStyle(color: Colors.black),)),
          TextButton(onPressed: ()=>{}, child: Text('Log in',style: TextStyle(color: Colors.black),)),
        ],
      ),
      body: Scrollbar(
        isAlwaysShown: true,
        child: SingleChildScrollView(
        child: Column(
          
          children: [
        Container(
          padding: EdgeInsets.symmetric(horizontal: page_padding/2),
          height: 100,
          child: Row(
            
            children: [
              Container(
                alignment: Alignment.centerLeft,
               
                width: (media.size.width-page_padding)*0.8,
                child: Text('Home',
                style: TextStyle(fontSize: 40, fontWeight: FontWeight.bold),),
              ),
              Container(
                
                width: (media.size.width-page_padding)*0.2,
                alignment: Alignment.centerRight,
                child: TextButton(onPressed: ()=>{Get.toNamed(Routes.MATTE)}, child: Text('upload new',
                style: TextStyle(fontSize: 20, color: Colors.black),
                )),
              )
              
            ],
          ),
        ),
        Container(
          padding: EdgeInsets.only(left: page_padding/2,right: page_padding/2,top: 10,bottom: 10),
          alignment: Alignment.centerLeft,
       
          child: Text('Get inspired',
          style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),),
        ),
        Container(
          alignment: Alignment.centerLeft,
          padding: EdgeInsets.only(left: page_padding/2,right: page_padding/2,bottom: 10),
          child: Text('check out these photos generated by creators',
          style: TextStyle(fontSize: 15),),
        ),
        Container(
          padding: EdgeInsets.symmetric(horizontal: page_padding/2),
          child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Container(
              padding: EdgeInsets.all(3),
              height: 500,
              width: (media.size.width-page_padding)/3,
              child: Image(image: AssetImage('images/test.jpg')),
            ),
            Container(
              padding: EdgeInsets.all(3),
              height: 500,
              width: (media.size.width-page_padding)/3,
              child: Image(image: AssetImage('images/test.jpg')),
            ),
            Container(
              padding: EdgeInsets.all(3),
              height: 500,
              width: (media.size.width-page_padding)/3,
              child: Image(image: AssetImage('images/test.jpg')),
            ),
         
          ],
        ),
        ),
        Container(
          alignment: Alignment.centerLeft,
          padding: EdgeInsets.only(left: page_padding/2,right: page_padding/2,top: 10,bottom: 10),
          child: Text('Your products',
          style: TextStyle(fontSize: 30,fontWeight: FontWeight.bold),),
        ),
        Container(
          alignment: Alignment.centerLeft,
          padding: EdgeInsets.only(left: page_padding/2,right: page_padding/2,bottom: 10),
          child: Text('click on product to get started',
          style: TextStyle(fontSize: 15),),
        ),
        Container(
          padding: EdgeInsets.symmetric(horizontal: page_padding/2),
          child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Container(
              padding: EdgeInsets.all(3),
              height: 500,
              width: (media.size.width-page_padding)/3,
              child: Image(image: AssetImage('images/test.jpg')),
            ),
            Container(
              padding: EdgeInsets.all(3),
              height: 500,
              width: (media.size.width-page_padding)/3,
              child: Image(image: AssetImage('images/test.jpg')),
            ),
            Container(
              padding: EdgeInsets.all(3),
              height: 500,
              width: (media.size.width-page_padding)/3,
              child: Image(image: AssetImage('images/test.jpg')),
            ),
         
          ],
        ),
        ),
        
      ]),
      ),)
      
      
    );
  }
}